export const CLOUDINARY_ASSETS = {
  homeBanner1:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352847/techeducoder/local-assets/1.jpg",
  homeBanner2:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352848/techeducoder/local-assets/2.jpg",
  homeBanner3:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352850/techeducoder/local-assets/3.jpg",
  homeBannerCopy:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352849/techeducoder/local-assets/3-copy.jpg",
  mobileBanner1:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352869/techeducoder/local-assets/mobile.jpg",
  mobileBanner2:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352870/techeducoder/local-assets/mobile1.jpg",
  faqBanner:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352873/techeducoder/local-assets/saaa.png",
  avatar:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352850/techeducoder/local-assets/assests/avatar.png",
  business:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352852/techeducoder/local-assets/assests/business-img.png",
  siteLogo:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352874/techeducoder/local-assets/TEC-logo-By-UniqueIIT-1500-x-500-px-1.svg",
  logo:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352867/techeducoder/local-assets/logo.svg",
  nextLogo:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352871/techeducoder/local-assets/next.svg",
  vercelLogo:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352876/techeducoder/local-assets/vercel.svg",
  image:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352865/techeducoder/local-assets/image.png",
  bannerImage:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352851/techeducoder/local-assets/assests/banner-img-1.png",
  client1:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352853/techeducoder/local-assets/assests/client-1.jpg",
  client2:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352854/techeducoder/local-assets/assests/client-2.jpg",
  client3:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352855/techeducoder/local-assets/assests/client-3.jpg",
  darkLogoSvg:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352856/techeducoder/local-assets/assests/drk.svg",
  lgo1:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352858/techeducoder/local-assets/assests/lgo1.png",
  logoh:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352859/techeducoder/local-assets/assests/logoh.png",
  uniqueIitDarkLogo:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352862/techeducoder/local-assets/assests/UniqueIIT-Dark-Logo-1.png",
  uniqueIitLightLogo:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352863/techeducoder/local-assets/assests/UniqueIIT-Light-Logo-1.svg",
  generatedDarkLogo:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352860/techeducoder/local-assets/assests/svgtopng-1-/drk.png",
  generatedUniqueIitDarkLogo:
    "https://res.cloudinary.com/techuniqueiit/image/upload/v1786352861/techeducoder/local-assets/assests/svgtopng-1-/UniqueIIT-Dark-Logo-1.png",
} as const;
